---

- name: Enable Web Server (IIS) (Web-Server)
  win_feature:
    name: Web-Server
    state: present

- name: "Enable Additional Web Server Roles"
  win_feature:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ iis_enable_roles }}"

- name: "Disable Some Web Server Roles"
  win_feature:
    name: "{{ item }}"
    state: absent
  with_items:
    "{{ iis_disable_roles }}"
